import './Styles/globals.css';
import type { Metadata } from 'next';
import '@fontsource/inter'; 

export const metadata: Metadata = {
  title: 'Ibeneme Ikenna, Amboss Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className='fonr-inter'>{children}</body>
    </html>
  );
}
